// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hphraxvqbquaykflwjzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaHJheHZxYnF1YXlrZmx3anpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzc0MzMsImV4cCI6MjA3MjI1MzQzM30.kOevHJ4uMyI7ZscDy37yW8c8XnZwrI6vinw6FqSUhpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});