- name: Deploy dist/ to Hostinger (FTP)
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ${{ secrets.FTP_SERVER }}         # 147.93.14.207
    username: ${{ secrets.FTP_USERNAME }}     # u234345696.digitalmarketcontrole.shop
    password: ${{ secrets.FTP_PASSWORD }}
    protocol: ftp
    server-dir: /public_html/                 # <<< CAMINHO CORRETO
    local-dir: dist/
    dangerous-clean-slate: false
    exclude: |
      **/.git*
      **/.github/**
